### Schema
DROP DATABASE IF EXISTS m0b85542v73htil6;

CREATE DATABASE m0b85542v73htil6;

USE m0b85542v73htil6;

DROP TABLE IF EXISTS burgers;

CREATE TABLE burgers
(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	devoured BOOLEAN DEFAULT false,
    createdAt TIMESTAMP default CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);

